import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Suspense } from "react";
import LoadingUI from "@/components/LoadingUI";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "TenKun Movie",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="w-full min-h-screen bg-black flex justify-center ">
          {children}
        </div>
      </body>
    </html>
  );
}
